name: Manual Auth Pipeline Deployment

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: choice of which auth pipeline will be deployed
        options:
          - rules
          - actions

jobs:
  deploy-rules-auth-pipeline:
    if: inputs.choice == 'rules'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet rules
        run: |
          echo "rules chosen"

  deploy-actions-auth-pipeline:
    if: inputs.choice == 'actions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet actions
        run: |
          echo "actions chosen"

