name: Manual Auth Pipeline Deployment

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: choice of which auth pipeline will be deployed
        options:
          - rules
          - actions
        required: true
      environment:
        type: environment
        description: environment to deploy selected auth pipeline to
        required: true
env:
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}

jobs:
  deploy-rules-auth-pipeline:
    if: inputs.choice == 'rules'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Node
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm i -g auth0-deploy-cli@^7

      - name: clean file system for rules auth pipeline deployment
        run: |
          echo "file system before cleaning"
          ls
          rm -r actions
          rm -r attack-protection
          rm -r branding
          rm -r clients
          rm -r connections
          rm -r custom-domains
          rm -r database-connections
          rm -r emails
          rm -r grants
          rm -r guardian
          rm -r pages
          rm -r prompts
          rm -r resource-servers
          rm -r roles
          rm -r triggers
          rm -r migrations.json
          rm -r tenant.json
          echo "file system after cleaning"
          ls
          echo "check deploy cli version"
          a0deploy --version
          chmod +x deleteAuthPipeline.js
          npm i axios
          node deleteAuthPipeline.js ${{ secrets.token }} actions matthew.ciam-sandbox.thomsonreuters.com
          echo "{\"AUTH0_DOMAIN\":\"matthew.ciam-sandbox.thomsonreuters.com\",\"AUTH0_CLIENT_ID\":\"PQuCDN3M1oJiW1LMN1nY9opscJWy7wHk\",\"AUTH0_CLIENT_SECRET\":\"$AUTH0_CLIENT_SECRET\",\"AUTH0_ALLOW_DELETE\":false}" > config.json
          cat config.json
          a0deploy import -c=config.json --input_file=.

  deploy-actions-auth-pipeline:
    if: inputs.choice == 'actions'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Node
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm i -g auth0-deploy-cli@^7

      - name: clean file system for actions auth pipeline deployment
        run: |
          echo "file system before cleaning"
          ls
          rm -r rules
          rm -r attack-protection
          rm -r branding
          rm -r clients
          rm -r connections
          rm -r custom-domains
          rm -r database-connections
          rm -r emails
          rm -r grants
          rm -r guardian
          rm -r hooks
          rm -r pages
          rm -r prompts
          rm -r resource-servers
          rm -r roles
          rm -r migrations.json
          rm -r tenant.json
          echo "file system after cleaning"
          ls
          echo "check deploy cli version"
          a0deploy --version
          chmod +x deleteAuthPipeline.js
          npm i axios
          node deleteAuthPipeline.js ${{ secrets.token }} rules matthew.ciam-sandbox.thomsonreuters.com
          a0deploy import -c=config.json --input_file=.
