name: Manual Auth Pipeline Deployment

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: choice of which auth pipeline will be deployed
        options:
          - rules
          - actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: greet
        run: |
          echo "choice for auth pipeline deployment is ${{ inputs.choice }}"

      - name: deploy rules
        if: inputs.choice == 'rules'
        steps:
          run: |
            echo "rules"

      - name: deploy actions
        if: inputs.choice == 'actions'
        steps:
          run: |
            echo "rules"