name: Testing file

on:
  workflow_dispatch:

env:
  THE_ENVIRONMENT: ${{ vars.THE_ENVIRONMENT }}

jobs:
  testing-environment:
    runs-on: ubuntu-latest
    environment: sandbox
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: echo the environment using the environment vars feature
        run: echo $THE_ENVIRONMENT
